### ISSUE TITLE
Deprecation Warning `ssl.wrap_socket()`

### ISSUE THREAD

**Issue by exploide** [zyn3rgy/LdapRelayScan#9] opened 2022-05-05 12:52 UTC
On Python 3.10.4 I get the following deprecation warning when running the tool.

```
LdapRelayScan.py:121: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
```

**Comment by iditabad** [comment] 2022-05-19 13:02
A fix for this was submitted in pull request #10 :)

**Comment by 0xJs** [comment] 2022-07-27 09:22
Playing around with both versions and I can't get it to work completely:

![image](https://user-images.githubusercontent.com/43987245/181211834-f8180caf-e496-41c7-8a0f-75e13b768d1b.png)

![image](https://user-images.githubusercontent.com/43987245/181211884-033752b1-92f4-4404-9833-80a8f059ba22.png)

Worked eventually with the normal version but not with your pr @iditabad . Hopefully you can do something with this info :)

**Comment by iditabad** [comment] 2022-07-30 02:20
Hmmmm okay thanks, I'll take a look and figure out what happened!

**Comment by iditabad** [comment] 2022-07-30 02:32
It actually looks like this is something that was just accepted before but now throws an error, so I'll talk with @zyn3rgy but maybe we just remove that error altogether, or maybe we just throw the error and continue instead of dying.

Thanks again for pointing this out @0xJs

**Comment by 0xJs** [comment] 2022-07-31 13:42
Thanks :)

**Comment by zyn3rgy** [comment] 2022-10-06 19:48
Couldn't reproduce. Closing for now but will reopen if the issue persists.

**Closed by zyn3rgy** 2022-10-06 19:48 UTC

**Comment by exploide** [comment] 2022-10-08 12:08
Thanks for the response @zyn3rgy but the issue persists.

In https://github.com/zyn3rgy/LdapRelayScan/blob/da2bf1f7d1521d54ddf969a1dd7849982cffd377/LdapRelayScan.py#L123 LdapRelayScan uses `ssl.wrap_socket(...)` but this is deprecated since Python 3.7, see https://docs.python.org/3/library/ssl.html#ssl.wrap_socket

> Deprecated since version 3.7: Since Python 3.2 and 2.7.9, it is recommended to use the [SSLContext.wrap_socket()](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_socket) instead of [wrap_socket()](https://docs.python.org/3/library/ssl.html#ssl.wrap_socket). The top-level function is limited and creates an insecure client socket without server name indication or hostname matching.

And this produces the warning message shown in the previous comments.

If the message doesn't appear for you, this could have various reasons. Maybe your version of python is older (I'm using 3.10.7 here), or some configuration setting / environment variable disables printing deprecation warnings.

Anyway, the legacy `ssl.wrap_socket(...)` functionality will be completely removed in Python 3.11, which will be released soon.
